version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./bot.db:/app/bot.db
      - ./5445047061721511293.jpg:/app/5445047061721511293.jpg
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
